version: '3'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./envs/.env
    ports:
      - 3000:3000
    depends_on:
      - mongodb
  
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - db_data:/data/db

volumes:
  db_data: